version: "3.3"
services:
  frontend:
    image: fgiannotti/tacs-tp-integrador-grupo-4-front
    ports:
      - "3000:3000"
  backend:
    image: lolokip/tacs-tp-integrador-grupo-4
    ports:
      - "9000:9000"
