version: "3.3"
services:
  frontend:
    image: fgiannotti/tacs-tp-integrador-grupo-4-front
    ports:
      - "3000:3000"
  backend:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - database
  database:
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: tacs
    volumes:
        - ./mysql-script:/docker-entrypoint-initdb.d