version: "3"
 
services:
  jenkins:
    user: root
    image: "jenkinsci/blueocean"
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge
